### PR TITLE
docs: update Heroku docs

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by msakrejda** [comment]
Thanks for the update! We'll review this soon.

**Review by keiko713 — APPROVED** [review]
Thanks for updating this, and sorry that it took long time to get back to you!
I just happened to check this new flow and confirmed that it works well. Also thanks for updating the log drain's `your-collector-app-domain-name` part (I wasn't reading your change well and I got bitten by this 😂).

I have some follow-up updates that I'd love to make (e.g. I'd like to move the setup documentation under auto_explain directory, do auto-explain in app check, etc. like we do in Azure: https://github.com/pganalyze/pganalyze-docs/pull/206), but I'll merge this as is and will do that as a follow-up.

I'll merge this after merging https://github.com/pganalyze/pganalyze-docs/pull/239 to minimize the confliction of updating in-app side.

**Comment by msakrejda** [comment]
Thanks, @keiko713! I'll let you run with this.

**Comment by bf4** [comment]
Thanks @keiko713 
Followed by https://github.com/pganalyze/pganalyze-docs/pull/241

**Pull request merged**
