### PR TITLE
Update get_column_stats for Postgres 17

### PR DESCRIPTION
**Pull request by seanlinsley**
On Postgres 17, the function breaks:

```sql
select * from pganalyze.get_column_stats() limit 1;
ERROR:  return type mismatch in function declared to return pg_stats
DETAIL:  Final statement returns too few columns.
CONTEXT:  SQL function "get_column_stats" during startup
```

Note that this documentation update makes it so this function definition no longer works for previous versions of Postgres. Do we have a UI pattern to handle this, like a tabbed component that lets you switch between PG 16 and 17 versions of the function?

This error wouldn't have occurred if the function didn't `RETURNS SETOF pg_stats`, instead choosing to return its own row type. If we don't plan to use the new fields, maybe we should change the return type instead of adding the new fields?

Here's the documentation for the new fields. IIRC this function is intended to return all data points that are not considered sensitive (don't include user data), so I've chosen to return null for `range_bounds_histogram`

Screenshot 2024-10-09 at 11 05 37 AM

### CODE REVIEW

**Comment by lfittl** [comment]
> This error wouldn't have occurred if the function didn't `RETURNS SETOF pg_stats`, instead choosing to return its own row type. If we don't plan to use the new fields, maybe we should change the return type instead of adding the new fields?

Yeah, that seems reasonable, and is how we solved this for `pg_stats_ext`.

@msakrejda Any concerns with changing this? (AFAIK you were involved in the original discussion on this for extended stats with Keiko and myself, though maybe I'm misremembering)

**Comment by msakrejda** [comment]
Looks like that was in #217--that doesn't seem to have any discussion on using the raw type versus TABLE, but I think TABLE makes more sense. +1 on changing pg_stats to do that until we need those fields.

And for what it's worth, we do have a way of doing version-specific instructions. #135 dropped that since that dropped 9.6 support and all supported versions could use identical instructions, but we can bring it back if necessary.

**Comment by seanlinsley** [comment]
How do we communicate this to everyone without it turning into a support ticket when they upgrade to Postgres 17? It's not even as simple as pointing them to the documentation since the function signature changed, so `CREATE OR REPLACE FUNCTION` doesn't work; they'll need to drop the existing function.

**Comment by msakrejda** [comment]
Oh, also, these are duplicated [here](https://github.com/pganalyze/collector/blob/main/runner/generate_helper_sql.go#L16-L24) :frowning:.

**Comment by msakrejda** [comment]
Re: the upgrade problem—I suppose we could have the collector recognize the old function definition at startup and print instructions?

**Review by msakrejda — APPROVED** [review]

**Comment by LukasJK** [comment]
I think the troubleshooting pages still need updating?

**Pull request merged**
